### ISSUE TITLE
Using png images

### ISSUE THREAD

**Issue by agwatic** [Rolinh/libgwavi#6]
I need to use `PNG` images instead of `JPG ` images used in the example. I tried it on the example but it doesn't work. how should I do it?

**Comment by rolinh** [comment]
The example works for `JPG` images because it uses the motion JPEG format (check the FourCC in the example). I'm not sure of the equivalent for `PNG` (if one exists). Maybe [CorePNG](https://wiki.multimedia.cx/index.php/CorePNG)? Otherwise, you always have the possibility of converting your `JPG` images to `PNG`.

**Comment by agwatic** [comment]
Ok.
what about using one of these extensions for images : ("bmp", "png", "ppm", "xbm", "xpm") ?
Do you know how to implement one of these on the example?

**Comment by rolinh** [comment]
Just convert the images to jpg? Example using [imagemagick](https://www.imagemagick.org):

```
$ convert image.jpg image.png
```

**Comment by agwatic** [comment]
I figured out how to extract jpg images from my code and use it into the example. Thanks alot @Rolinh
